# Generated by Django 3.1.4 on 2021-05-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocId', models.CharField(max_length=100)),
                ('DocName', models.CharField(max_length=100)),
                ('Doc_Mail', models.EmailField(max_length=100)),
                ('Date_Time', models.DateTimeField(max_length=100)),
                ('Specilization', models.CharField(default='', max_length=100)),
                ('Patient_Name', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('catagories_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('Catagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='task_group.catagories')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
