# Generated by Django 3.1.4 on 2021-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('doctor', 'DOCTOR'), ('patient', 'PATIENT')], default='doctor', max_length=10)),
            ],
        ),
    ]
