# Generated by Django 3.1.4 on 2021-05-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
