# Generated by Django 3.1.4 on 2021-05-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0003_auto_20210519_0213'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_table',
        ),
    ]
