# Generated by Django 3.1.4 on 2021-05-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0004_auto_20210519_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.CharField(choices=[('doctor', 'DOCTOR'), ('patient', 'PATIENT')], default='doctor', max_length=10),
        ),
    ]
